# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop
- DataSharing
- release/*


pool:
  vmImage: 'ubuntu-latest'

variables:
  framework: 'netcoreapp3.1'
  buildConfiguration: 'Release'
  architecture: 'linux-x64'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Dotnet Restore'
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Build'
  inputs:
    command: 'build'

- task: DotNetCoreCLI@2
  displayName: 'Run tests'
  inputs:
    command: 'test'

- task: DotNetCoreCLI@2
  displayName: 'Dotnet Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '-c $(buildConfiguration) -f $(framework) --self-contained false -r $(architecture) -o $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: 'DbMigration/DbMigration.csproj'
    arguments: '-c $(buildConfiguration) -f $(framework) --self-contained false -r win-x64 -o $(Agent.BuildDirectory)'
    zipAfterPublish: false

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Agent.BuildDirectory)'
    ArtifactName: 'migration'
    publishLocation: 'Container'